TodoList/Controllers/TodoController.cs
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using TodoList.Models;

namespace TodoList.Controllers
{
    public class TodoController : Controller
    {
        private readonly ApplicationDbContext db;

        public TodoController(ApplicationDbContext context)
        {
            db = context;
        }

        public IActionResult Index()
        {
            var todos = db.TodoItems.ToList();

            return View(todos);
        }

        public async Task<IActionResult> Details(int id)
        {
            var todo = await db.TodoItems.SingleOrDefaultAsync(x => x.Id == id);
            if (todo == null)
            {
                return HttpNotFound();
            }
            return View(todo);
        }

        public IActionResult Create()
        {
            ViewBag.Priority = new SelectList(Enumerable.Range(1, 4), "Priority"
                           );
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TodoItemEditModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var todo = new TodoItem
            {
                Title = model.Title,
                IsDone = model.IsDone,
                Priority = model.Priority
            };

            db.TodoItems.Add(todo);
            await db.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id)
        {
            var todo = await db.TodoItems.SingleOrDefaultAsync(x => x.Id == id);
            if (todo == null)
            {
                return HttpNotFound();
            }

            return View(todo);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, TodoItemEditModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var todo = await db.TodoItems.SingleOrDefaultAsync(x => x.Id == id);
            if (todo == null)
            {
                return HttpNotFound();
            }

            todo.Title = model.Title;
            todo.IsDone = model.IsDone;

            // TODO Exception handling
            db.SaveChanges();

            return RedirectToAction("Index", new { id = id });
        }

        // GET: TodoItems/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult((int)HttpStatusCode.BadRequest);
            }
            TodoItem todoItem = await db.TodoItems.SingleOrDefaultAsync(x => x.Id == id);
            if (todoItem == null)
            {
                return HttpNotFound();
            }
            return View(todoItem);
        }

        // POST: TodoItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            TodoItem todoItem = await db.TodoItems.SingleOrDefaultAsync(x => x.Id == id);
            db.TodoItems.Remove(todoItem);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
            //return RedirectToAction("Details", new { id = 1 });
        }

        public IActionResult IndexFinal()
        {
            var todos = db.TodoItems.ToList();

            return View(todos);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TodoList/ViewComponents/PriorityListViewComponent.cs
using Microsoft.AspNet.Mvc;
using System.Linq;
using System.Threading.Tasks;
using TodoList.Models;

namespace TodoList.ViewComponents
{
    public class PriorityListViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext db;

        public PriorityListViewComponent(ApplicationDbContext context)
        {
            db = context;
        }
        
        public IViewComponentResult Invoke(int maxPriority)
        {
            var items = db.TodoItems.Where(x => x.IsDone == false
                                             && x.Priority <= maxPriority);

            return View(items);
        }

        public async Task<IViewComponentResult> InvokeAsync(int maxPriority, bool isDone)
        {
            string viewName = "Default";

            // If asking for all completed tasks, render with the "PVC" view.
            if (maxPriority > 3 && isDone == true)
            {
                viewName = "PVC";
            }

            var items = await GetItemsAsync(maxPriority, isDone);

            return View(viewName, items);
        }

        private Task<IQueryable<TodoItem>> GetItemsAsync(int maxPriority, bool isDone)
        {
            return Task.FromResult(GetItems(maxPriority, isDone));
        }

        private IQueryable<TodoItem> GetItems(int maxPriority, bool isDone)
        {
            var items = db.TodoItems.Where(x => x.IsDone == isDone
                                             && x.Priority <= maxPriority);

            string msg = $"Priority <= { maxPriority } && isDone == { isDone }";
            ViewBag.PriorityMessage = msg;

            return items;
        }
    }
}

TodoList/Views/ToDo/Create.cshtml
@model TodoList.Models.TodoItemEditModel
    
@{
    ViewBag.Title = "Create a ToDo Item";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken();
    
    <div class="form-group">
        @Html.LabelFor(x => x.Title)
        @Html.EditorFor(x => x.Title)
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.IsDone)
        @Html.EditorFor(x => x.IsDone)
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Priority);
        @Html.DropDownList("Priority", String.Empty)
</div>

    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-default" />
    </div>
}

TodoList/Views/ToDo/Delete.cshtml
@model TodoList.Models.TodoItem

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TodoItem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TodoList/Views/ToDo/Details.cshtml
@model TodoList.Models.TodoItem

@{
    ViewBag.Title = "Details";
}

<div class="row">
    <div class="col-md-4">
        <table>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <td>
                    @Html.DisplayFor(model => model.Title)
                </td>
            </tr>

            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.IsDone)
                </th>
                <th>
                    @Html.DisplayFor(model => model.IsDone)
                </th>
            </tr>

            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Priority)
                </th>
                <th>
                    @Html.DisplayFor(model => model.Priority)
                </th>
            </tr>

        </table>
    </div>
</div>

TodoList/Views/ToDo/Edit.cshtml
@model TodoList.Models.TodoItem

@{
    ViewBag.Title = "Edit a Todo Item";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken();

    <div class="form-group">
        @Html.LabelFor(x => x.Title)
        @Html.EditorFor(x => x.Title)
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.IsDone)
        @Html.EditorFor(x => x.IsDone)
    </div>

    <div class="form-group">
      @Html.LabelFor(x => x.Priority);
      @Html.EditorFor(x => x.Priority);
    </div>

      <div class="form-group">
        <input type="submit" value="Save" class="btn btn-default" />
      </div>
      }

TodoList/Views/ToDo/Index.cshtml
@inject TodoList.Services.StatisticsService Statistics

@{
   ViewBag.Title = "Home Page";
}

<div class="jumbotron">
   <h1>ASP.NET 5</h1>
</div>
<div class="row">
   <div class="col-md-4">
      @if (Model.Count == 0)
      {
         <h4>No Todo Items</h4>
      }
      else
      {
         <table>
            <tr><th>TODO</th><th></th></tr>
            @foreach (var todo in Model)
            {
               <tr>
                  <td>@todo.Title </td>
                  <td>
                     @Html.ActionLink("Details", "Details", "Todo", new { id = todo.Id }) |
                     @Html.ActionLink("Edit", "Edit", "Todo", new { id = todo.Id }) |
                     @Html.ActionLink("Delete", "Delete", "Todo", new { id = todo.Id })
                  </td>
               </tr>
            }
         </table>
      }
      <div>@Html.ActionLink("Create New Todo", "Create", "Todo") </div>
   </div>

    <div class="col-md-4">
        @*@Component.Invoke("PriorityList", 2)*@
        @await Component.InvokeAsync("PriorityList", 4, true)
    </div>

    <div class="col-md-4">
        <h3>Stats</h3>
        <ul>
            <li>Total Todo's: @await Statistics.GetCount()</li>
            <li>Completed: @await Statistics.GetCompletedCount()</li>
            <li>Average Priority: @await Statistics.GetAveragePriority()</li>
        </ul>
    </div>
</div>

TodoList/Views/ToDo/IndexFinal.cshtml
@inject TodoList.Services.StatisticsService Statistics

@{
   ViewBag.Title = "Home Page";
}

<div class="jumbotron">
   <h1>ASP.NET 5</h1>
</div>
@* Markup removed for brevity *@
<div class="row">
   <div class="col-md-4">
      @if (Model.Count == 0)
      {
         <h4>No Todo Items</h4>
      }
      else
      {
         <table>
            <tr><th>TODO</th><th></th></tr>
            @foreach (var todo in Model)
            {
               <tr>
                  <td>@todo.Title </td>
                  <td>
                     @Html.ActionLink("Details", "Details", "Todo", new { id = todo.Id }) |
                     @Html.ActionLink("Edit", "Edit", "Todo", new { id = todo.Id }) |
                     @Html.ActionLink("Delete", "Delete", "Todo", new { id = todo.Id })
                  </td>
               </tr>
            }
         </table>
      }
      @* Markup removed for brevity *@
      <div>@Html.ActionLink("Create New Todo", "Create", "Todo") </div>
   </div>

   <div class="col-md-4">
      @await Component.InvokeAsync("PriorityList", 2, false)

      <h3>Stats</h3>
      <ul>
         <li>Items: @await Statistics.GetCount()</li>
         <li>Completed:@await Statistics.GetCompletedCount()</li>
         <li>Average Priority:@await Statistics.GetAveragePriority()</li>
      </ul>
   </div>
</div>